# To support Alpine, need to either add bash or fcheck needs to add support to switch shells
# FROM alpine as alpine

FROM debian:stretch

WORKDIR /app

COPY ./bin/0.3.0/fcheck /bin
COPY ./test/fcheck-config.toml /bin/fcheck-config.toml

CMD ["/bin/fcheck", "--config-file", "/bin/fcheck-config.toml"]
