version: '3.7'

services:
  fcheck:
    build: 
      context: .
      target: debian-stretch
    volumes:
      - ./actual:/actual
      - ./expected:/expected:ro
      - ./output:/output
      # Make sure to mount the file, not the folder to /bin
      # - ./bin/0.3.1/fcheck:/bin/fcheck
      - ./config:/config
