# [[test]]
# name = "test1"
# description = "Write two files and check they are the same"
# disabled = false
# timeout = 5000
# [test.input]
# type = "command"
# command = "echo \"Dogs\" > ./data/dogs.txt"
# delay = 20
# [test.output]
# type = "command"
# command = "echo \"Dogs\" > ./data/cats.txt"
# [test.validate]
# type = "command"
# command = "wdiff ./data/dogs.txt ./data/cats.txt"


# [[test]]
# name = "test2"
# disabled = false
# timeout = 5000
# [test.input]
# type = "command"
# command = "echo \"Dogs\" > ./data/dogs.txt"
# delay = 20
# [test.output]
# type = "command"
# command = "echo \"Dogss\" > ./test-data/cats.txt"
# [test.validate]
# type = "command"
# command = "wdiff ./test-data/dogs.txt ./test-data/cats.txt"


[[test]]
name = "ping zookeeper"
description = "ping zookeeper server"
disabled = false
timeout = 5000
[test.input]
type = "command"
command = "nc -z zookeeper 2182 > /dev/null 2>&1"
timeout = 5000
delay = 20
[test.output]
type = "command"
command = "ping zookeeper"
timeout = 5000
[test.validate]
type = "command"
command = "ping zookeeper"
timeout = 5000


# [[test]]
# name = "test3"
# disabled = true
# delay = 10
# timeout = 5000
# [test.input]
# type = "file"
# operation = "copy"
# fileFrom = "./test-data/test-file1.json"
# fileTo = "./test-data/accounts-2019-01-01.json"
# [test.output]
# type = "kafka"
# kafka-host = "localhost:9092"
# topic = "accounts"
# validation = [
#   "some data",
#   "other data"
# ]

[[test]]
name = "test4"
disabled = true
timeout = 5000
[test.input]
type = "command"
command = "cp ./test-data/test-file1.json ./test-data/accounts-2019-01-01.json"
delay = 20
[test.output]
type = "command"
command = "kafkacat -b localhost:9092 -t mysql_users -C ./somefilename.txt > output-data.txt"
[test.validate]
type = "command"
command = "xdiff correct-output.txt output-data.txt"
# what is success?

[[test]]
name = "test5"
disabled = true
timeout = 5000
[test.input]
type = "command"
command = "cat ./test-data/input-data.json > kafkacat -b localhost:9092 -t accounts -P"
delay = 20
[test.output]
type = "command"
command = "kafkacat -b localhost:9092 -t accounts -C > ./test-data/output-data.txt"
[test.validate]
type = "command"
command = "xdiff correct-output.txt output-data.txt"
# what is success?
